<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html lang="en-US"itemscope itemtype="http://schema.org/medicalcondition">
  <head>
    <title>Gout | What happened to my foot last night?</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <meta property="twitter:account_id" content=""/>
        <link rel="canonical" href=""/>
        <!-- fb -->
        <meta name="og:title" content="Gout | What happened to my foot last night?"/>
        <meta name="og:url" content=""/>
        <meta name="og:description" content="Gout is a type of arthritis (inflammation of the joints) that mostly affects men age 40 and older. It is caused by chronic hyperuricemia--a long-lasting, abnormally high concentration of uric acid in the blood."/>
        <meta name="og:image" content=""/>
        
        <!-- twitter -->
        <meta name="Twitter:card" content="summary"/>
        <meta name="Twitter:site" content="@"/>
        <meta name="Twitter:creator" content="@"/>
        <meta name="Twitter:title" content=""/>
        <meta name="Twitter:url" content=""/>
        <meta name="Twitter:description" content=""/>
        <meta name="Twitter:image"/>

        <!-- Google+ -->
        <meta itemprop="name" content="Gout | What happened to my foot last night?"/>
        <meta itemprop="description" content="Gout is a type of arthritis (inflammation of the joints) that mostly affects men age 40 and older. It is caused by chronic hyperuricemia--a long-lasting, abnormally high concentration of uric acid in the blood."/>
        
        <meta itemprop="image" content=""/>
        
                
              
        <link rel="author" href="http://plus.google.com/113774021362941412953" />
        
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
        <link rel="icon" href="/favicon.ico" type="image/x-icon">









    <!-- Bootstrap -->
    <link href="../../css/bootstrap.css" rel="stylesheet">
    <!--<link href="css/font-awesome.min.css" rel="stylesheet">-->
    <link href="../../css/mystyles.css" rel="stylesheet">
    <!-- <link href="css/glyphicons.css" rel="stylesheet"> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <meta http-equiv="X-UA-Compatible" content="IE=9">
  </head>

  <body id="gout">

  <?php include '../components/navhead.php'; ?>



  <div class="navibar">
    <section class="container">
  
      <div class="pull-left">
        <p>Gout<p>
      </div><!-- pullleft -->
      <div class="pull-right">
        <ol class="breadcrumb">
            <li><a href="../../index.php">Home</a></li>
            <li><a href="/pathology/pathology.php">Conditions</a></li>
            <li class="active">Gout</li>
        </ol><!-- breadcrumb -->
      </div><!-- pull-right -->
     
    </section><!-- container -->
  </div><!-- navibar -->

  <!-- end navibar -->
<div class="layoutspacing2"></div>

<div class="container">
  
<ul class="nav nav-tabs nav-justified" style="margin: 20px 0px;">
              <li class="active"><a href="#cause" data-toggle="tab">Summary</a></li>
              <li><a href="#signs_symptoms" data-toggle="tab">In Depth</a></li>
              <li><a href="#treatment" data-toggle="tab">Video</a></li>
             
            </ul>

            <!-- Tab panes -->
           
            <div class="tab-content" style="padding: 0px 60px;">
              <div class="tab-pane fade in active" id="cause">
                 <h4 style="text-align: center;"><img src="/images/pathology/goutfoot.jpg" alt="Typical appearance of an acute gouty attack" /></h4> <p itemprop="cause">Gout is caused by abnormal metabolism of substances called purines that result in the accumulation of uric acid in the blood stream. Purines are a by-product of cell break down. When the excretion of the uric acid is hampered the accumulated uric acid in the blood stream causes crystalline deposits to form in joints or in the soft tissues. When this happens, there is a sudden onset of extreme pain with associated swelling, redness, and increased warmth to the skin or joint. Classic gout occurs in the big toe joint. It can occur in other joints as well but is rarely seen in more than one joint at a time.</p> <p>
                  <span itemprop="cause">As the crystalline deposits form in the joints and soft tissue, the uric acid levels in the blood stream can return to normal. Blood tests taken during an attack of gout may be within normal levels. This can make diagnosis more difficult, and the physician must rely on his or her clinical experience to make the diagnosis.</span>  <span itemprop="signorsymptom">An attack of gout can resemble an infection. An elevated temperature may also be present. This is worrisome to the physician because an infection in a joint can be a very damaging event.</span></p> <p style="text-align: center;"><img src="/images/pathology//goutflowchart.jpg" alt="Flow Chart The Cause of Gout purines to uric acid to urate crystals" /></p> 
               </div>
              <!-- tab -->
              <div class="tab-pane fade" id="signs_symptoms">
                  <h3>In Depth</h3> <p>Gout is a type of arthritis (inflammation of the joints) that mostly affects men age 40 and older. It is <span itemprop="cause">caused by chronic hyperuricemia--a long-lasting, abnormally high concentration of uric acid in the blood.</span> <span itemprop="pathophysiology">Purines, nitrogen-containing compounds, are the chemical sources of uric acid and can be divided into two types, endogenous and exogenous</span>. <span itemprop="pathophysiology">Endogenous purines are synthesized within the nuclei of cells in the human body itself, whereas the exogenous purines are obtained from foods. Uric acid is the end product of purine metabolism and is mostly produced in the liver. From there it enters the bloodstream. Most of uric acid eventually passes through the kidneys and is excreted in the urine; the rest is disposed of in the intestines, where it is processed and oxidized by bacteria.</span><br /> <br />
                  Normally these processes keep the concentration of uric acid in the blood plasma (the liquid part of the blood) below 7 milligrams per deciliter (7 mg/dL). Under certain circumstances, however, the body produces too much uric acid or excretes too little, resulting in levels above 7 mg/dL--the point at which hyperuricemia develops. <span itemprop="pathophysiology">In the bloodstream, uric acid exists predominantly as a dissolved salt called monosodium urate (MSU).</span> At 37 degrees C (normal body temperature) and at a uric acid concentration approaching 7 mg/dL, the blood plasma becomes supersaturated, and needlelike crystals of MSU form. Crystallization is governed by other factors as well. In joints, such as the knee and ankle, temperatures are cooler (29 degrees C to 32 degrees C), and MSU crystals are able to form at even lower uric acid concentrations, which explains why gout favors these joints. In time, MSU crystals can provoke an inflammatory response that produces the symptoms characteristic of gout. In respect to gout, humans are less fortunate than many animals, which never suffer from gout because they possess uricase, an enzyme that converts uric acid to allantoin, a substance much more easily excreted by the kidneys.<br /> <br /> <br /> </p> <h4>What Causes Gout?</h4> <p>
                  <span itemprop="stage">Gout is classified as either primary (the most common type) or secondary, depending on the cause of the associated hyperuricemia. In both types of gout, between 70% to 95% of hyperuricemia cases are the result of underexcretion of uric acid, rather than uric acid overproduction.</span><br /> <br /> </p> <h4>Primary Gout.</h4> <p>
                  <span itemprop="pathophysiology">Hyperuricemia in primary gout arises or is presumed to arise from a genetic or other inborn disorders that cause metabolic problem resulting in overproduction of uric acid or reduced excretion of uric acid. More than 99% of primary gout cases, however, are idiopathic, meaning that the cause of the hyperuricemia cannot be determined.</span> The remaining cases are traceable to either of two rare inherited enzyme defects that affect purine synthesis in the cells.<br /> <br /> </p> <h4>Secondary Gout.</h4> <p>
                  In <span itemprop="pathophysiology">secondary gout, hyperuricemia is caused by drug therapy or by medical conditions other than an inborn metabolic disorder.</span><br /> <br />
                  Medications. <span itemprop="cause">Thiazide diuretics (the "water pills" used to control hypertension) cause hyperuricemia by decreasing uric acid excretion. The list of drugs that cause hyperuricemia is long and includes not only diuretics but also pyrazinamide (used to treat tuberculosis) and the immunosuppressive drug cyclosporine (given to transplant recipients to prevent organ rejection). Low doses of aspirin and other salicylates decrease uric acid excretion, whereas high doses have the opposite effect.</span><br /> <br />
                  Kidney Disorders. <span itemprop="cause">Renal (meaning kidney) insufficiency is the impaired ability of the kidneys to eliminate waste products, including uric acid, which then build up in the blood. Gout is associated with three primary disorders that can cause renal insufficiency: urate nephropathy; uric acid nephropathy; and uric acid nephrolithiasis.</span><br /> <br />
                  Urate nephropathy occurs when monosodium urate crystals form in kidney tissue is uncommon and researchers believe that it usually causes only minor kidney damage.<br /> <br />
                  Uric acid nephropathy is a disorder that occurs uric acid crystals from urine forming in the structures and tubes that carry fluid from the kidney. It most often occurs during chemotherapy for lymphoma or leukemia. It can result in kidney failure by obstructing urine flow, but is preventable and reversible.<br /> <br />
                  Uric acid nephrolithiasis occurs when kidney stones form from uric acid. Uric acid and other kidney stones are present in 10% to 25% of patients with primary gout--a prevalence more than 1000 times that in the general population. In secondary gout, the reported incidence reaches 42%. Uric acid stones can also form in the absence of gout or hyperuricemia. Not all of the kidney stones in patients with gout are composed of uric acid; some are composed of calcium oxalate, calcium phosphate, or those substances combined with uric acid. Kidney stones can be extraordinarily painful and can cause infection and kidney failure if untreated.<br /> <br />
                  Other Medical Conditions. A number of diseases, including leukemia, lymphoma, and psoriasis, can cause gout. Over exposure to lead can cause gout.<br /> <br />
                  Alcohol Use. Alcohol use increases uric acid levels in three ways: by providing an additional dietary source of purines (the compounds from which uric acid is formed); by intensifying the body's production of uric acid; and by interfering with the kidneys' ability to excrete uric acid.<br /> <br />
                  Purine-Rich Diet. A purine-rich diet rarely causes hyperuricemia, although it may precipitate an attack in some people with existing gout. [For a list of purine-rich foods, see What Lifestyle Measures Can Help Prevent Gout?, below.]<br /> <br /> </p> <h4>What Are The Symptoms Of Gout?</h4> <p>
                  Gout is often divided by experts into four symptomatic stages: <span itemprop="stage">asymptomatic hyperuricemia, acute gouty arthritis, intercritical gout, and chronic tophaceous gout.</span> <span itemprop="cause">Gout symptoms can be precipitated by stress, infection, joint injury, weight loss, surgery, certain kinds of drug treatment, overindulgence in alcohol or purine-rich foods, or even something as seemingly inconsequential as a long walk that one was not sufficiently physically fit to undertake.</span>  </p> <h4>Asymptomatic Hyperuricemia.</h4> <p>
                  Asymptomatic hyperuricemia always precedes gout and is considered the first stage of the disorder. It can last, however, for an average of 30 years. Hyperuricemia also does not inevitably lead to gout. In fact, less than 20% of the hyperuricemic population develops this arthritic disease.<br /> <br /> </p> <h4>Acute Gouty Arthritis.</h4> <p>
                  Acute gouty arthritis is the stage at which the first symptoms of gout appear. Sometimes gout is heralded by brief twinges of pain (petit attacks) in an affected joint, which can precede the actual full-blown condition by several years.<br /> <br />
                  Symptoms usually begin as a sudden, severe, and unexpected arthritic attack affecting a single joint in one of the lower limbs, a <span itemprop="possible complication">condition known as monoarticular gout. The joint of the big toe is the site of about half of all first gout attacks--a specific condition called podagra. The site is often medically referred to as the big toe's metatarsophalangeal (MTP) joint--the point where one of the long five bones of the foot meets the first digit of a toe.</span><br /> <br />
                  <span itemprop="associatedanatomy">The joints of the foot, ankle, knee, wrist, elbow, and hand are other frequently affected sites. In such cases the condition is known as polyarticular gout.</span> More than one joint is affected in 10% to 20% of first attacks. The pain usually occurs in joints on one side of the body and it usually, although not alway in the lower extremities. People with polyarticular gout are more likely to have a more gradual onset of pain and a longer delay between attacks. They also more likely to experience a low-grade fever, loss of appetite, and a general feeling of unwellness.<br /> <br />
                  The primary symptom, which usually takes eight to 12 hours to develop, is <span itemprop="signorsymptom">severe, sometimes crushing pain at and around the joint. In many cases the attack occurs late at night or early in the morning and announces itself by waking the sufferer.</span> <span itemprop="signorsymptom">Some patients describe it as resembling a disoclated bone and one writer described it as "like walking on my eyeballs". Chills and mild fever may follow. The area can be so tender that walking and even the weight of bedsheets can be unbearable. Swelling may extend beyond the joint, indicating fluid build-up within. The skin over the affected area is often red, shiny, and tense. After a few days it may start to peel. An untreated attack will typically peak 24 to 48 hours after the initial appearance of symptoms, and subside after five to seven days, although it can last only hours to several weeks.</span><br /> <br /> </p> <h4>Intercritical Gout.</h4> <p>
                  Intercritical gout is the term used to describe the periods between attacks. The first attack is usually followed by a complete remission of symptoms, but in untreated cases most people can expect a recurrence. One study found that 62% of subjects experienced at least one further attack within a year. At the end of two years 78% and after 10 years 93% of patients experienced a recurrence of gout.<br /> <br /> </p> <h4>Chronic Tophaceous Gout.</h4> <p>
                  When gout remains untreated, the intercritical periods typically become shorter and shorter, and the attacks--although sometimes less intense--can last longer. Gout may also eventually affect several joints, including those that may have been free of symptoms at the first appearance of the disorder. In rare cases, the shoulders, hips, or spine are affected. Over the long term--about 10 to 20 years--in untreated gout the intercritical periods dwindle until gout becomes a chronic disorder characterized by constant low-grade pain and mild or acute inflammation in several joints. Persistent gout, moreover, can destroy cartilage and bone, causing irreversible joint deformities and loss of motion.<br /> <br />
                  Tophi. After several years, persistent gout can produce tophi, which are solid deposits of MSU crystals that form in the joints and elsewhere in the body (hence the term chronic tophaceous gout). Without anti-hyperuricemia treatment, tophi develop on average about 10 years after the onset of the disease although their first appearance can range from three to 42 years. Bones, cartilage, tendons, soft tissue, and membranes containing synovial fluid (the lubricating fluid surrounding joints) can all harbor tophi. Common locations include the helix of the outer ear (the curved ridge along the edge of the ear), the fingers, hands, forearms, knees, and feet, and the olecranon bursa (a sac at the elbow joint filled with synovial fluid). In some cases, tophi break through the skin and appear as white or yellowish-white chalky nodules. (They have been described as looking like "crabs eyes.") Although tophi themselves are generally painless, they often cause pain and stiffness in an affected joint and can erode cartilage and bone, ultimately destroying the joint. Large tophi under the skin of the hands and feet can give rise to extreme deformities. In rare cases, they can settle in regions around the heart and spine. Today, drug therapy has reduced the prevalence of chronic tophaceous gout to as little as 3%, although certain groups, such as transplant patients receiving cyclosporine, still face a high risk of developing tophi.<br /> <br /> </p> <h4>How Serious Is Gout?</h4> <p>
                  In the past, gout often developed into a painful and disabling chronic disorder. Tophi could destroy bone and cartilage in the joints, similar to rheumatoid arthritis. But now, after several decades of research into the causes of gout and the development of drugs for controlling hyperuricemia, gout rarely poses a long-term threat to health if properly treated. Still, it remains a source of short-term pain and incapacity for thousands of Americans.<br /> <br />
                  Although gout itself is not life-threatening, it is often associated with serious diseases. Diabetes and obesity are very common in gout patients as well as high blood pressure and kidney disease. Kidney disease, in fact, is more common in gout patients than in people with diabetes. (Gout, however, is more likely to be caused by kidney problems than is hyperuricemia the cause of kidney abnormalities.) Kidney stones are also common in people with gout and occur in between 10% and 40% of patients. Usually the stones are composed of uric acid but they may also be formed from other materials.<br /> <br /> </p> <h4>Who Gets Gout?</h4> <p><br /> </p> <h4>Prevalence.</h4> <p>
                  Gout is one of the most common types of arthritis. In the United States there were an estimated 2.2 million cases of self-reported gout in 1986, and a 1991 publication noted that Americans lost an estimated 37 million working days a year to gout. It is estimated that approximately 15 of every 1,000 American males between 35 and 45 years of age have gout and some experts believe that one in 100 men may be at risk for it. It is very uncommon in less developed countries and in 1952 it was said to be unkown in China, Japan, the tropics, and rare among African Americans. The prevalence of gout not only in America but in other developed countries has, however, been rising in recent decades, possibly because of dietary and lifestyle changes, greater use of medications that cause hyperuricemia, and aging populations.<br /> <br /> </p> <h4>Gender and Age Differences</h4> <p>
                  <span itemprop="epidemiology">Gout typically strikes only after 20 to 40 years of persistent hyperuricemia and men tend to have higher uric acid levels than women. For these reasons, men over 40 years old account for about 90% of the population affected by gout.</span> Among children, the levels of uric acid are the same for both genders (an average of 3 to 4 milligrams (mg) of uric acid per deciliter (dL) of plasma. Male levels rise substantially at puberty, with the result that the level exceeds 7 mg/dL (considered to indicate hyperuricemia and an increased risk for gout) in about 5% to 8% of American men. For many men, hyperuricemia begins in puberty and may last a lifetime. Less than 5% of patients with gout are female. The female hormone estrogen appears to facilitates uric acid excretion by the kidneys (the body's chief mechanism for disposing of uric acid), so levels in women remain essentially stable until menopause, after which they approach male levels. Premenopausal women are thus much less likely than men of the same age to be hyperuricemic, and whereas men usually experience their first attack of gout between the ages of 30 and 50 years old, women are more likely to experience gout between the ages of 50 and 70. Rare inherited genetic disorders that cause hyperuricemia can result in gout in children.<br /> <br /> </p> <h4>Family History.</h4> <p>
                  <span itemprop="epidemiology">A fairly substantial proportion of patients with gout (10% to 20%) have a family history of gout, but it is not known if genetics, environmental factors, or both play roles in this association.</span><br /> <br /> </p> <h4>Other Risk Factors.</h4> <p>
                  Risk factors are attributes or activities associated with a greater-than-normal likelihood of developing a particular disorder (as in the case of obesity and heart disease, or smoking and lung cancer). Sometimes a causal connection between the attribute or activity and the disorder can be established, but at other times there is simply a statistical correlation. The risk factors for gout, of which there are several, are identical to those for hyperuricemia.<br /> <br />
                  Obesity. <span itemprop="riskfactor">Researchers report a clear link between body weight and uric acid levels and have also discovered that obesity is an especially important risk factor in men.<br /> <br />
                  Hypertension. Hypertension (high blood pressure) is found in 25% to 50% of patients with gout, but whether it causes hyperuricemia is uncertain.</span><br /> <br />
                  Alcohol use. Alcohol use is associated with gout and in one study, it was the only notable risk factor for women with gout.<br /> <br /> </p> <h4>How Is Gout Diagnosed?</h4> <p>
                  Standard diagnostic tools for gout may include a medical history and physical examination, a blood test for hyperuricemia, and urine sample. For a definitive diagnosis of gout, a sample of synovial fluid from the affected joint is required. X-rays can provide helpful information in some cases.<br /> <br /> </p> <h4>Ruling Out Other Disorders.</h4> <p>
                  As part of the diagnostic process other disorders that resemble gout symptoms or cause hyperuricemia should be ruled out. Some experts believe both gout and pseudogout are underdiagnosed in hospital patients resulting in incorrect therapy--for example antibiotics for cellulitis, a serious infection that has symptoms similar to those of gout.<br /> <br />
                  Pseudogout. Pseudogout is a condition most likely to be confused with gout. It is caused by deposits of calcium pyrophosphate dihydrate crystals in and around the joints. Though pseudogout resembles gout in some ways, the first attack typically strikes the knee rather than the joint of the big toe, and at least two-thirds of cases affects more than one joint. The symptoms of pseudogout also appear more slowly than those of gout, taking days rather than hours to develop.<br /> <br />
                  Other Causes of Arthritic Pain. The symptoms of gout can resemble those of many other disorders, including acute rheumatic fever, rheumatoid arthritis, traumatic arthritis, osteoarthritis, serious skin infections, hallux rigidus (painful stiffness in the first joint of the big toe), and Reiter's syndrome (a disorder characterized by arthritis, urethritis, and conjunctivitis). Many of these disorders can be present at the same time as gout.<br /> <br /> <br />
                  Other Causes of Hyperuricemia. Binge drinking, fasting, lead toxicity, leukemia, certain uncommon anemias, multiple myeloma, and lymphomas are also uncommon causes of high uric acid concentrations.<br /> <br /> <br /> <br />
                  
                   <h4>Medical History and Physical Examination.</h4> <p>
                  Determining which joints are affected in a patient suspected of having gout is an obvious first step in any diagnosis. A physician is more likely to suspect gout as the cause of an acute attach of arthritis if it first appears in the first joint of the big toe than it if arthritis attacked, for example, a shoulder or hip. The examiner also needs to determine whether the onset of pain and swelling was rapid, for symptoms that require days or weeks rather than hours to develop probably indicate a disorder other than gout. Another possible indicator of gout is previous damage to an affected joint, because gout often arises in injured joints.<br /> <br /> </p> <h4>Blood Test.</h4> <p>
                  A blood test is usually given, although some experts argue that it isn't necessary, given what is now known about the variability of uric acid levels in people with gout. Uric acid levels in the blood during an attack of gout do not necessarily mirror levels before the attack, and in fact can lie within or below the normal range. Even if hyperuricemia is present, it is very common in the population and does not necessarily indicate the presence of gout. A low level of uric acid in the blood however, makes a diagnosis of gout much less probable, and a very high level increases the likelihood of gout.<br /> <br /> </p> <h4>24-Hour Urine Sample.</h4> <p>
                  It is sometimes helpful to gauge the amount of uric acid excreted by the patient over the course of 24 hours, particularly if the patient is young and has pronounced hyperuricemia that might be related to a metabolic disorder. If the amount exceeds a particular value, further tests for an enzyme defect or other identifiable cause of gout arising from uric acid overproduction are justified. Greater-than-normal amounts of uric acid in the urine also indicate that the patient faces a greater risk of developing uric acid kidney stones, and can guide the physician in his or her choice of drug therapy for chronic gout. The urine is collected during an intercritical period, after the patient has been placed on a purine-reduced diet. The patient is also asked to temporarily stop using alcohol and any medications that can interfere with the test. On the first day of the test, the urine passed by the patient on waking up in the morning is discarded, but for the next 24 hours the patient collects all of his or her urine in a special container. The test concludes the next morning with the patient urinating into the container right after waking up. The container is then delivered to the patient's physician or sent directly to the laboratory.<br /> <br /> </p> <h4>Examination of Synovial Fluid.</h4> <p>
                  The synovial fluid is the lubricating liquid that fills the synovium, the membrane that surrounds a joint and creates a protective sac. In addition to cushioning joints, this fluid supplies nutrients and oxygen to cartilage, the slippery tissue that coats the ends of bones. The procedure for taking a sample of synovial fluid from an affected joint is called aspiration. A needle attached to a syringe is inserted into the joint and suction is used to draw the fluid into the syringe. Local anesthesia is avoided because it can reduce the effectiveness of aspiration, but normally the procedure is only mildly uncomfortable. Following the procedure there can be some minor discomfort in the area where the needle was inserted, but it usually dissipates quickly. Aspiration can cause infection, though this occurs in less than 0.1% of patients. After the sample is taken, it is sent to a laboratory, where a microscope is used to look for monosodium urate (MSU) crystals, which can be detected with polarized light. The laboratory can also test the sample for infection (always a possibility in cases of gout). Another benefit of aspiration is that it sometimes eases a patient's symptoms by reducing swelling and pressure on the tissue surrounding the joint.<br /> <br /> </p> <h4>X-Rays.</h4> <p>
                  For the most part, x-rays do not reveal any abnormalities during the early stages of gout, and their usefulness where gout is concerned lies in assessing the progress of the disorder in its chronic phase and in identifying other health problems whose symptoms may resemble those of gout. Tophi can be seen on x-rays before they become apparent on physical examination.<br /> <br /> </p> <h4>Trial of Colchicine.</h4>
                    <h4>How Is Gout Treated?</h4> <p><br /> </p> <h4>General Guidelines.</h4> <p>
                  Acute attacks of gout and long-term treatment of gout and its associated hyperuricemia require different approaches. All phases are mainly treated mainly with drugs. There are also specific treatment regimes for cause common causes of gout, including uric acid nephropathy and uric acid nephrolithiasis.<br /> <br />
                  Treatments for Asymptomatic Hyperuricemia.Because asymptomatic hyperuricemia usually does not lead to gout or other health problems, and would have to be treated with drugs that present certain risks and can be expensive, treatment to prevent a first attack of gout in hyperuricemic patients is considered inadvisable. In unusual circumstances, for example when very high uric acid levels create a risk of kidney toxicity, treatment may be justified.<br /> <br />
                  Treatment of Acute Gouty Arthritis. Drug treatments for acute attacks of gout are aimed at relieving pain and reducing inflammation. Powerful forms of nonsteroidal anti-inflammatory drugs (NSAIDs are the drugs of choice for an acute attack. Colchicine or corticosteroids may also be used. Rest, applying cold, and protecting the affected joint with a splint can also promote recovery. Acute attacks respond best to immediate treatment. After the first attack, some physicians advise their patients to keep a supply of medications for an acute attack on hand so that self-medication can begin at the first sign of symptoms.<br /> <br />
                  Treatment for Intercritical Period and Tophaceous Gout. During the period between gout attacks, patients are advised to avoid foods high in purines and to maintain a healthy weight. Patients should also avoid alcohol and reduce any stress. Many patients do not require medications. Usually preventive drug therapy is used only if there are two or three attacks that occur within a year. Some physicians prescribe low-dose NSAIDs or colchicine to prevent recurrent attacks. Increasing the dose when a patient believes an attack is pending can often abort it. These are simply anti-inflammatory drugs, however, and have no effect on hyperuricemia.<br /> <br />
                  The goals of antihyperuricemic therapy are to reduce uric acid levels to normal, decrease the frequency of attacks, and to dissolve monosodium urate (MSU) crystals and tophi. Allopurinol and drugs known as uricosurics, which include probenecid and sulfinpyrazone, are available for these purposes and are all very effective. Which drug to prescribe depends on individual conditions [ see Specific Drugs for Long-Term Treatment, below]. When and if to prescribe them at all, however, is not entirely clear. Some physicians do not prescribe them if hyperuricemia is mild and not until a patient has had two attacks. Others prescribe them immediately after a single attack. It should be noted that any of these drugs can actually precipitate acute gout symptoms and so should not used until symptoms have subsided, and then the patient should start with small doses that gradually increase. Colchicine or an immediate-acting NSAID, such as naprosyn, should be given during the initial months of therapy to prevent symptoms attacks. Most of the time, antihyperuricemic therapy means taking a drug routinely throughout life, which many people find difficult to adhere to. In rare cases, surgery is used to treat the effects of chronic gout.<br /> <br /> </p> <h4>Specific Drugs Used for Acute Attacks.</h4> <p>
                  <span itemprop="possibletreatment">Nonsteroidal Anti-Inflammatory Drugs (NSAIDs). Nonsteroidal anti-inflammatory drugs (NSAIDs block prostaglandins, the substances that dilate blood vessels and cause inflammation and pain.</span> They are taken orally at their highest safe dosage as long as symptoms persist and for three or four days after. There are dozens of NSAIDs. Indomethacin (Indocin) is the usual choice for gout; ibuprofen, naproxen, sulindac, or others are good alternatives particularly for elderly patients who might experience confusion or bizarre sensations with indomethacin [ see below]. The first dose of indomethacin usually begins to act against the pain and inflammation of gout within 24 hours, and often much sooner.<br /> <br />
                  Taking NSAIDs with food can reduce discomfort, although it may slow down the pain-relieving effect. All NSAIDs are capable of damaging the mucous layer and causing ulcers and gastrointestinal (GI) bleeding when taken for long periods. They also appear to delay the emptying of the stomach, which may interfere the actions of other drugs. The elderly are at special risk for GI bleeding. Younger nonsmoking adults adapt better to NSAIDs. Bleeding and ulcers can occur at any time, with or without symptoms. The risk for bleeding is continuous as long as a patient is on these drugs and may even persist for about a year after taking them. No NSAIDs should be used for long-term pain relief except under a physician's direction. One study ranked the sixteen most commonly used NSAIDs according to GI toxicity. Those at lowest risk were nabumetone (Relafen), etodolac (Lodine), salsalate, and sulindac (Clinoril). At medium risk were aspirin, diclofenac (Voltaren), ibuprofen (Motrin, Advil, Nuprin, Rufen), naproxen (Aleve, Naprosyn, Naprelan, Anaprox), and tolmetin (Tolectin). Drugs within this group, however, vary in risk. Studies show, for example, that short-term use of naproxen is twice as likely as ibuprofen to be associated with hospitalization from GI bleeding. Although ketoprofen (Actron, Orudis, Oruvail) was considered medium risk, one study reported that even one week of taking the drug at low doses causes significant GI injury. The highest risk for GI bleeding were from flurbiprofen (Ansaid), piroxicam (Feldene), fenoprofen, indomethacin (Indocin), meclofenamate (Meclomen), and oxaprozin (Daypro). Others not compared in this analysis were diflunisal (Dolobid), and ketorolac (Toradol).<br /> <br />
                  <span itemprop="possibletreatment">A gel containing ibuprofen can be applied to sore joints and may have less risk for gastrointestinal side effects.</span> Studies suggest that taking the drug omeprazole (Prilosec), known as a proton-pump inhibitor, along with NSAIDs can both heal and help prevent NSAID-related ulcers. Misoprostol (Cytotec) is a drug that is also commonly used to prevent NSAID-induced ulcers. A drug (Arthrotec) that combines diclofenac and misoprostol is proving had 65% to 80% fewer ulcers than those patients who took NSAIDs alone. Unfortunately misoprostol has its own side effects that include diarrhea, cramps, and gas. Common antacids, or H2 blockers, such as ranitidine (Zantac), cimetidine (Tagamet), famotidine (Pepcid), and nizatidine (Axid), reduce symptoms caused by gas but do not keep NSAIDs from causing ulcers. In fact, such drugs may pose a danger by masking symptoms of developing ulcers.<br /> <br />
                  Other side effects of NSAIDs include dizziness, ringing in the ear, headache, and skin rash. Depression has also been noted. Kidney damage has been reported in people taking NSAIDs, which resolves when the drugs are withdrawn. (Aspirin has little or no risk for this side effect.) NSAIDs may also increase blood pressure, particularly in those on medications to reduce hypertension. Piroxicam (Feldene), naproxen (Aleve), and indomethacin (Indocin) appear to pose the greatest risks for high blood pressure. Sulindac (Clinoril has the smallest effect. People with hypertension, severe vascular disease, kidney, or liver problems, and those taking diuretics must be closely monitored if they need to take NSAIDs. Any sudden weight gain or swelling should be reported to a physician. Because NSAIDs reduce the clotting of the blood, anyone undergoing surgery should stop taking the medication a week before the operation. Diabetics taking oral hypoglycemics may need to adjust the dosage if they also need to take NSAIDs because of possible harmful interactions between the drugs. Alcohol abuse may increase the risks for bleeding.<br /> <br />
                  <span itemprop="possibletreatment">Colchicine. Colchicine, a derivative of the autumn crocus (also called the meadow saffron), has been used against gout for centuries. It is highly effective though no longer the first drug of choice because of its frequent and unpleasant side effects. Although colchicine usually eliminates the pain of an acute attack within 48 hours, it is unsuitable for many patients because of nausea, vomiting, diarrhea, or abdominal cramps after taking the drug.</span> Colchicine is usually taken orally, but can be administered intravenously to patients who are unable to take oral medications because of severe gastrointestinal side effect or if oral administration is not possible. The intravenous route is riskier, however, and poses an incresaed risk for harmful effects in the kidney, liver, central nervous system, and bone marrow. The oral regimen requires doses every hour until the patient either improves or side effects develop; improvement should be evident by the tenth dose. Cimetidine (Tagamet) and the antibiotic erythromycin can intensify the side effects of colchicine, so patients taking those drugs need to be monitored and their use of colchicine halted if they begin to suffer gastrointestinal difficulties. Colchicine is not appropriate for patients with kidney, liver, or bone marrow disorders.<br /> <br />
                  Corticosteroids. The corticosteroids, known commonly as steroids, are used only when patients cannot tolerate other anti-inflammatory drugs or they are ineffective. They include triamcinolone (administered by injection) and prednisone (taken orally). Corticotropin (ACTH), a drug that converts to a steroid, is another option. Oral doses are usually given for seven to 10 days. A single injection is usually sufficient. If only one joint is affected, an injection may be administered directly to the site. Corticosteroids are sometimes followed by a rebound attack of gout after treatment is completed. To prevent this colchicine is given two or three times daily with the steroid and for several days after discontinuing it. They should only be administered for short periods and not used for long-term treatment.<br /> <br /> </p> <h4>Specific Drugs for Long-Term Treatment.</h4> <p>
                  Long-term treatment of hyperuricemia is recommended for tophi prevention and when the patient has suffered several acute attacks of gout over a number of years, when the attacks are unusually severe or affect more than one joint, or when hyperuricemia is caused by an identifiable inborn metabolic deficiency.<br /> <br />
                  Allopurinol. <span itemprop="possibletreatment">Allopurinol (Lopurin, Zyloprim) blocks uric acid production and is the drug most often used in long-term treatment for older patients and those with high levels of excreted uric acid (over 800 mg during a 14-hour period). It is also considered the drug of choice for patients with impaired kidney function, a history of kidney stones, and for tophaceous gout.</span> Allopurinol is taken orally only once a day in doses of 100 mg to 600 mg, depending on the patient's response to treatment. The drug's side effects, experienced by 3% to 5% of patients, include skin rashes, leukopenia (a reduction in the number of white blood cells), thrombocytopenia (a reduction in the number of platelets), diarrhea, headache, and fever. When they are first used, allopurinol and the uricosurics can trigger further attacks of gout, and thus during the first months (or longer) of antihyperuricemic therapy the patient is also given an NSAID or colchicine to forestall that possibility. Some patients experience an allergic reaction to allopurinol, which can be fatal. However, allergic patients may be able to build up their tolerance for the drug by undergoing a desensitization process. It may also increase the risk for cataracts.<br /> <br />
                  Uricosuric Drugs. <span itemprop="possibletreatment">Probenecid (Benemid, Parbenem, Probalan) and sulfinpyrazone (Anturane) are uricosurics, which are drugs that prevent the kidney from reabsorbing uric acid and so increase the amount excreted in the urine.</span> Uricosuric drugs are usually the choice for patients under 60 years old who have normal diets and kidney function and have no risk of kidney stones. Uricosuric drug candidates should also produce no more than 700 to 800 mg of uric acid in urine over a 24-hour period. These drugs may actually intensify gout symptom if they are not started until acute attacks have stopped. The initial doses should be low and then gradually build up. Adding low-dose colchicine or an NSAID may help prevent gout attacks. Although allopurinol's side effects tend to be substantially more severe than with the uricosurics, many prefer allopurinol because it is only taken once a day. Probenecid is taken twice to three times a day and sulfinpyrazone begins at twice a day and increases to three or four times daily. The possible side effects of these two drugs include skin rashes, gastrointestinal problems, anemia, and kidney stone formation. Sufficient fluid intake is important to help reduce acidity and so prevent uric acid kidney stones. To also reduce the urine acidity as quickly as possible, patients may also be given sodium bicarbonate supplemented by acetazolamide. NSAIDs, particularly aspirin, as well as other salicylate drugs, interfere with these drugs and reduce effectiveness, so they should be avoided; patients who require minor pain relief should take acetaminophen (Tylenol and others). Uricosurics also interact with many other drugs, and a patient should be sure to inform the physician of any medications they are taking. A uricosuric combined with allopurinol is occasionally effective in cases where using just one drug is not. Probenecid combined with colchicine is more effective than probenecid alone, but patients respond differently to this regimen depending on the dosage balance, so it needs to be carefully individualized.<br /> <br />
                  Colchicine and NSAIDs. Low doses of NSAIDs or colchicine are used to prevent gout attacks in patients who are starting anti-hyperuricemic therapies. For patients who cannot take either allopurinol or a uricosuric, low daily doses of oral colchicine provide a possible alternative treatment for hyperuricemia, though not among patients with renal insufficiency or liver disease.<br /> <br /> </p> <h4>Surgery.</h4> <p>
                  Surgery is sometimes used to remove large tophi that are draining, infected, or interfering with the movement of joints. Several other surgical procedures are available for relieving pain in and improving the function of affected joints. It is sometimes necessary to replace joints.<br /> <br /> </p> <h4>Treatment for Pseudogout.</h4> <p>
                  There is no cure for pseudogout, but there are treatments to relieve the pain and inflammation and reduce the frequency of attacks. NSAIDs are effective for treating inflammation and pain from pseudogout. For acute attacks in large joints, fluid aspiration along or with steroids may help. Intravenous colchicine is also helpful but may be toxic. Pseudogout is a progressive disorder that can destroy joints, and joint replacement may be required.<br /> <br /> </p> <h4>Treatment of Kidney Disorders That Can Cause Gout.</h4> <p>
                  Uric Acid Nephropathy. Uric acid nephropathy is common in chemotherapy patients. In such cases it is preventable if they are adequately hydrated and given allopurinol before chemotherapy begins. Treatment has reduced the death rate in cases of uric acid nephropathy from about 50% to close to zero.<br /> <br />
                  Uric Acid Nephrolithiasis. Uric acid stones are dissolved by giving the patient allopurinol to reduce the concentration of uric acid in his or her urine. The patient also takes oral sodium bicarbonate or acetazolamide (Diamox) to alkalinize the urine. Drinking at least 10 to 12 eight-ounce glasses of water and other nonalcoholic beverages every day is important as well. [For more information see Kidney Stones.]<br /> <br /> </p> <h4>What Lifestyle Measures Can Help Prevent Gout?</h4> <p><br /> </p> <h4>Avoid Purine-Rich Foods.</h4> <p>
                  Because uric acid levels are only minimally affected by diet, dietary therapy does not play a large role in the prevention of gout. Still, people who have suffered an attack of gout may benefit from reducing their intake of purine-rich foods if they habitually eat unusually large quantities of such foods. They include They include beer and other alcoholic beverages, anchovies, sardines (in oil), fish roes, herring, yeast, organ meats (e.g., liver, kidneys), legumes (e.g., dried beans, peas, and soybeans), meat extracts, consommé, gravies, mushrooms, spinach, asparagus, cauliflower, and poultry.<br /> <br /> </p> <h4>Protein Restriction.</h4> <p>
                  Diets high in protein, particularly animal protein, increase uric acid. Although few studies have been conducted and none of determined the value of reducing protein, one study of gout patients suggested that eating tofu, which is made from soy and is a source of complete protein, may be a better choice than meats.<br /> <br /> </p> <h4>Maintain Healthy Weight.</h4> <p>
                  A supervised weight-loss program may, however, be a more effective way to reduce uric acid levels if the patient is overweight. Crash dieting, on the other hand, is counterproductive because it can increase uric acid levels and can cause an acute attack.<br /> <br /> </p> <h4>Maintain Fluids and Avoid Alcohol.</h4> <p>
                  Drinking plenty of water and other nonalcoholic beverages helps remove MSU crystals from the body. Heavy drinking, especially binge drinking of beer or distilled spirits, should be avoided, because alcohol is a source of purines and can also cause overproduction and underexcretion of uric acid.<br /> <br /> </p> <h4>Avoid Joint Injury.</h4> <p>
People with gout should also attempt to identify and avoid activities that cause repetitive joint trauma, such as the wearing of tight shoes.</p>
              </div>
              <!-- tab -->
              <div class="tab-pane fade" id="treatment">
                  <iframe width="560" height="315" src="http://www.youtube.com/embed/OVMzNaffL7E" frameborder="0"></iframe>
              </div>
              </div>
              
            </div><!-- tab0content -->

</div><!-- container -->

<!-- footer -->

   <?php include '../components/footer.php'; ?>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/modernizr.js"></script>
    <?php include '../../components/social.php'; ?>



  </body>
</html>