<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html>
  <head>
    <title>Hammertoes | Why are my toes curled?</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="../../css/bootstrap.css" rel="stylesheet">
    <!--<link href="css/font-awesome.min.css" rel="stylesheet">-->
    <link href="../../css/mystyles.css" rel="stylesheet">
    <!-- <link href="css/glyphicons.css" rel="stylesheet"> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <meta http-equiv="X-UA-Compatible" content="IE=9">
  </head>

  <body id="hammertoes">

  <?php include '../components/navhead.php'; ?>



  <div class="navibar">
    <section class="container">
  
      <div class="pull-left">
        <h1>Hammertoes</h1>
      </div><!-- pullleft -->
      <div class="pull-right">
        <ol class="breadcrumb">
            <li><a href="../../index.php">Home</a></li>
            <li><a href="/pathology/pathology.php">Conditions</a></li>
            <li class="active">Hammertoes</li>
        </ol><!-- breadcrumb -->
      </div><!-- pull-right -->
     
    </section><!-- container -->
  </div><!-- navibar -->

  <!-- end navibar -->
<div class="layoutspacing2"></div>

<div class="container">
  
<ul class="nav nav-tabs nav-justified" style="margin: 20px 0px;">
              <li class="active"><a href="#cause" data-toggle="tab">Cause</a></li>
              <li><a href="#signs_symptoms" data-toggle="tab">Signs and Symptoms</a></li>
              <li><a href="#treatment" data-toggle="tab">Treatment</a></li>
             
            </ul>

            <!-- Tab panes -->
           
            <div class="tab-content" style="padding: 0px 60px;">
              <div class="tab-pane fade in active" id="cause">
                  <p>Hammertoes are one of the most common foot problems. A hammertoe is a curling of toe the joints, sometimes affecting one or both joints of the toe. This curling of the toes often leads to rubbing on shoe gear. This abnormal rubbing leads to painful and unsightly toes. Calluses and corns soon follow.</p> <p style="text-align: center;"><img alt="" src="/images/pathology/hammertoe.jpg" /></p>
                </div>
              <!-- tab -->
              <div class="tab-pane fade" id="signs_symptoms">
                  <h4>Cause:</h4> <p>Despite popular belief, curling of your toes is not due to poor choices of shoe gear. Rather, biomechanical factors are usually to blame. Biomechanics is the term used to describe how the foot and ankle move when you walk or stand. When we refer to someone as "flat footed" we are really describing is how biomechanics has affected their foot. Specifically, if the foot rolls in too much when you walk, we call that pronation. So a person who pronates has altered or abnormal biomechanics. When a person has normal biomechanics, there is an order motion to the muscles and joints of the feet and ankles. Altered, or abnormal biomechanics will lead to abnormal motion of the joints and muscles. Biomechanics then is used as a predictive model - telling us what happens to the foot in the presence of abnormal motions such as pronation.</p> <p>There are three distinct possible causes of hammertoes. Each is based on an abnormality in the biomechanics of the foot and ankle during the walking cycle.</p> <p style="text-align: center;"><img src="/images/pathology/toe.jpg" alt="Example of extensor and flexor tendons of the toe" /></p> <h4>Flexor Stabilization: </h4> <p>The flexors tendons are located on the bottom of the toe. These tendons should exert the same amount of force as their opposing tendons, the extensors tendons, which are located on the top of the toe. When the force generated by the contracture of the extensosr is equal to that of the flexors, the toe stays stablized during the walking cycle.</p> <p style="text-align: center;"><strong>Force of Extensors = Force of Flexors = Toe stays straight</strong></p> <p>In a person who is pronated or flat footed, the flexor tendons pull harder than the extensors, making the toe unstable during the walking cycle. Given enough time, this instability leads to a gradual curling of the toe. A hammertoe is born.</p> <p style="text-align: center;"><strong>Force of Flexors Force of Extensors = Unstable curled toe</strong></p> <h4>Extensor Substitution: </h4> <p>This condition is essentially the opposite of flexor stabilization. In this case, the extensor tendons over power the flexor tendons during the swing phase of the walking cycle(the foot swinging forward and off the ground). This leads to contracture of the toes. This phenomenon is commonly seen with people who have a very high arch.</p> <p style="text-align: center;"><strong>Force of Extensors  Force of Flexors = Curled Toe</strong></p> <h4>Flexor stabilization:</h4> <p>A weak calf muscle causes the flexor tendons of the foot to compensate, or carry more of the load. The flexor tendons overpower the extensors of the toe causing an unstable toe leading to curling.</p>
              </div>
              <!-- tab -->
              <div class="tab-pane fade" id="treatment">
                  <h3>Treatment:</h3> <p>As we have seen, most causes of hammertoes are a result of biomechanical problems of the foot. And while no conservative treatment can straighten the toes once curled, Treatments aim at correcting the underlying biomechanical abnormality can sometimes keep the toes from getting worse. The most effective biomechanical therapy are custom orthotics. These "arch supports" help to reestablish the normal force generated at the toe by the flexor and extensor tendons.</p> <p style="text-align: center;"><strong>Orthotics + Force of Flexors = Orthotics + Force of Extensors</strong></p> <h4>Other non-surgical treatments include:</h4> <ul> <li>Wearing shoes with larger toe boxed, preventing rubbing of the toes on the shoes.</li> <li>Wearing non-medicated padding over the boney prominence.</li> <li>Sanding the calluses on a regular basis.</li> </ul> <h3>Surgical:</h3> <p>Surgical treatment consist of stabilizing the toe during the walking cycle. This is done a number of ways, depending the stiffness of the toe, presence of other deformities and overall health o f the patient.</p>
              </div>
              </div>
              
            </div><!-- tab0content -->

</div><!-- container -->

<!-- footer -->

   <?php include '../components/footer.php'; ?>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/modernizr.js"></script>
    



  </body>
</html>