<html>
<head>
<!-- HTML meta URL redirect - generated by www.rapidtables.com -->
<meta http-equiv="refresh" content="0; url=http://podlink.herokuapp.com/pathology/heel-pain.php">
</head>
<body>
</body>
</html>